 variables:
  IMAGE_TAG: docker.selvas.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
  LATEST_TAG: docker.selvas.com/$CI_PROJECT_PATH:latest
  GIT_SUBMODULE_STRATEGY: recursive

 build:
   stage: build
   only: 
     - tags
   script:
     - docker build -t $IMAGE_TAG .
     - docker tag $IMAGE_TAG $LATEST_TAG
     - docker push $IMAGE_TAG
     - docker push $LATEST_TAG
